### ISSUE TITLE
Formatter may coalesce or split SMT-LIB tokens

### ISSUE THREAD

**Issue by bohlender** [symflower/smtfmt#1]
While implementing a proper scanner for [vim-smt2's auto-formatter](https://github.com/bohlender/vim-smt2/issues/2) I stumbled over minor issues with the testcase originally provided by you @krobelus. The issues are SMT-LIB specific, so if you aim for a generic Lisp formatter they might not be problematic for you at all.  They caught me by surprise so I wanted to make you aware of them :sweat_smile:

- The following line should probably not be considered as properly formatted:
https://github.com/symflower/smtfmt/blob/da3ac2335ff882e769d3dbf267136d0ceeff0594/smtfmt.py#L225
Here, `0.0.0.0:5900` is understood as a single symbol and correspondingly formatted as such. However, according to [the SMT-LIB token specification](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf#appendix.B), these are three separate tokens 
```
  pos  len            kind  lexeme
   26    3         decimal: 0.0
   29    4   simple_symbol: .0.0
   33    5         keyword: :5900
 ```
so the formatter should probably separate them by whitespace and consider putting them on separate lines.

- While the above example features three tokens that are treated as a single token, it can also happen that the formatter treats a single one as a bunch of tokens. For example, this happens when we have quoted symbols such as `| this is a single symbol |`.

There are some more cases that the formatter does not account for so I suggest just skimming the [token specification](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf#appendix.B) to decide whether the edge cases are worth being "fixed" for `smtfmt`.

**Comment by krobelus** [comment]
That's interesting, thanks! I'm currently not using this for any lisps other than SMT-LIB, so I guess I'll follow the spec until there is a concrete need for a more permissive formatter.

Your tokenization of `0.0.0.0` assumes that the longest rule wins. If the leftmost rule had precedence it would be

```
0        numeral
.0.0.0   simple_symbol
```

I'm not sure what's the convention here?

---

OT: I'm fairly happy with the behavior now - preserving blank lines from the input makes it bearable to always format on save.
The line-breaking heuristic could probably be improved but it's hard to find a general rule.
